/**
 * Freeze the engine's current output into `web/data/snapshot.json`.
 *
 * WHY THIS EXISTS. The dashboard's data layer shells out to `engine/cli.py` and
 * reads `../engine/**` off disk. Both are true on this box and false everywhere
 * else — a serverless host has no Python, no FRED key and no repo root above the
 * app. So the deployed dashboard reads a snapshot instead.
 *
 * The snapshot is GENERATED BY the Python CLI, never reimplemented. That keeps
 * the invariant lib/fed.ts was built around: one implementation of the reaction
 * function, so the cockpit and the CLI can never disagree.
 *
 * A snapshot is FROZEN, and the UI is obliged to say so — `generated_at` is
 * carried through to the page and rendered next to the number. A stale
 * prediction served as if it were live is the same class of error as quoting an
 * accuracy without its baseline.
 *
 * Class C — no model call, no spend. Run it, then redeploy.
 */
import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

const HERE = path.dirname(fileURLToPath(import.meta.url));
const WEB = path.resolve(HERE, "..");
const REPO = path.resolve(WEB, "..");
const ENGINE = path.join(REPO, "engine");
const OUT = path.join(WEB, "data", "snapshot.json");

/** How many past decisions to carry. The page renders the last 24. */
const HISTORY_KEEP = 40;

async function cli(args, timeoutMs) {
  const { stdout } = await execFileAsync("python", [path.join(ENGINE, "cli.py"), ...args], {
    cwd: ENGINE,
    timeout: timeoutMs,
    maxBuffer: 16 * 1024 * 1024,
  });
  return JSON.parse(stdout);
}

async function readJson(rel, { optional = false } = {}) {
  try {
    return JSON.parse(await fs.readFile(path.join(REPO, rel), "utf8"));
  } catch (err) {
    if (optional) return null;
    throw new Error(`could not read ${rel}: ${err.message}`);
  }
}

/**
 * Anything that could carry the FRED key never gets near this file, but the
 * check is cheap and the failure mode — publishing a key to a public URL — is
 * not recoverable by redeploying.
 */
function assertNoSecrets(text) {
  const hits = [];
  if (/FRED_API_KEY/i.test(text)) hits.push("FRED_API_KEY");
  if (/api_key=/i.test(text)) hits.push("api_key= query string");
  for (const m of text.match(/\b[0-9a-f]{32}\b/g) ?? []) hits.push(`32-hex token ${m.slice(0, 6)}…`);
  if (hits.length) {
    throw new Error(`refusing to write snapshot — possible secret in payload: ${hits.join(", ")}`);
  }
}

const [forecast, pathRows, backtest, current, decisions, tuning] = await Promise.all([
  cli(["predict", "--json"], 120_000),
  cli(["path", "--json", "--n=5"], 180_000),
  readJson("engine/models/backtest.json"),
  readJson("engine/models/current.json"),
  readJson("engine/data/decisions.json"),
  readJson("engine/models/tuning.json", { optional: true }),
]);

// `preds` is 233 prediction objects that nothing downstream reads — lib/fed.ts
// deletes it and fedSubset.mjs explicitly refuses to derive from it. Dropping it
// here keeps the bundled artifact small.
delete backtest.preds;

const snapshot = {
  generated_at: new Date().toISOString(),
  engine: {
    trained: forecast?.model?.trained ?? null,
    train_to: forecast?.model?.train_to ?? null,
    n_meetings: forecast?.model?.n_meetings ?? null,
  },
  forecast,
  path: pathRows,
  artifacts: {
    "engine/models/backtest.json": backtest,
    "engine/models/current.json": current,
    "engine/data/decisions.json": {
      decisions: (decisions?.decisions ?? []).slice(-HISTORY_KEEP),
    },
    "engine/models/tuning.json": tuning,
  },
};

const text = JSON.stringify(snapshot, null, 2);
assertNoSecrets(text);
await fs.writeFile(OUT, text + "\n", "utf8");

const kb = (Buffer.byteLength(text) / 1024).toFixed(0);
console.log(`snapshot -> data/snapshot.json  (${kb} KB)`);
console.log(`  meeting     ${forecast?.meeting}  (${forecast?.days_away} days away)`);
console.log(`  expected    ${forecast?.expected_bp?.toFixed?.(1)} bp`);
console.log(`  path rows   ${pathRows?.length ?? 0}`);
console.log(`  history     ${snapshot.artifacts["engine/data/decisions.json"].decisions.length}`);
